apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
      - name: simple-app
        image: asrulkw/simple-app:latest
        args: ["npm", "start"]
        # resources:
        #   limits:
        #     memory: "1082Mi"
        #     cpu: "1000m"
        ports:
        - containerPort: 3000